language: python
os: linux

git:
  depth: 1

osx_image: xcode10

dist: bionic

jobs:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows

before_script:
  # Install Austin
  if [[ "$TRAVIS_OS_NAME" == "linux" ]];
  then
    sudo snap install austin --classic;
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]];
  then
    choco install austin;
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]];
  then
    brew install austin;
  fi;

  pip install nox==2020.5.24;
  pip install poetry==1.0.5

script:
  nox
