name: Tests
on: push
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: Tests on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64

      - name: Install Austin from the Snap Store
        run: sudo snap install austin --classic
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install Austin from Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1
        if: startsWith(matrix.os, 'windows')
        with:
          args: install austin

      - name: Refresh PATH variable on windows
        run: refreshenv
        if: startsWith(matrix.os, 'windows')

      - name: Install Austin from Homebrew
        run: brew install austin
        if: startsWith(matrix.os, 'macos')

      - run: pip install nox==2020.5.24
      - run: pip install poetry==1.0.5

      - run: nox
        if: "!startsWith(matrix.os, 'macos')"

      - run: sudo nox
        if: startsWith(matrix.os, 'macos')

      - run: poetry run codecov
        if: startsWith(matrix.os, 'ubuntu')
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
